# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          author_name: $GITHUB_ACTOR
          author_email: github.action@jordinebot.cat

      - name: Setup git
        run: git config --global user.email "you@example.com" && git config --global user.name "Your Name"

      - name: Install Dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Test
        run: npm run test --silent

      - name: Bump up
        run: npm run version:bump
        run: git push origin $GITHUB_REF

