# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use node v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm ci

    - name: Build package
      run: npm run build

    - name: Test
      run: npm run test --silent

    - name: Bump up
      run: echo "GITHUB_REF = $GITHUB_REF"
      run: git config --global user.email "github.action@jordinebot.cat"
      run: git config --global user.name $GITHUB_ACTOR
      run: npm run version:bump
