name: Bump up Develop

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup git
        env:
          AUTHOR_NAME: Github Actions
          AUTHOR_EMAIL: github.action@jordinebot.cat
        run: git config --global user.email "$AUTHOR_EMAIL" && git config --global user.name "$AUTHOR_NAME"

      - name: Install Dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Test
        run: npm run test --silent

      - name: Step that prints name of pull request's base branch
        run: |
            echo "Pull request's base branch is: ${BASE_BRANCH}"
            echo "Pull request's head branch is: ${HEAD_BRANCH}"
        env:
            BASE_BRANCH: ${{ github.base_ref }}
            HEAD_BRANCH: $${{ github.head_ref }}

